version: "3"
services:
  lamp:
    container_name: myproject-web
    image: eurelis/aws-ami-php7
    volumes:
      - ./runtime/vhosts.conf.d:/etc/httpd/vhosts.conf.d
      - ./runtime/mysql:/var/lib/mysql
      - ./runtime/log:/var/log/httpd
      - ./runtime/scripts:/opt/scripts
      - ./runtime/web:/var/www/html
      - ./runtime/conf/.mybashrc:/root/.mybashrc
    ports:
      - 9080:80
      - 3306:3306
    env_file: ./my_project.env
    extra_hosts:
    # export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
      - "dockerhost:$DOCKERHOST"
